### ISSUE TITLE
的	frequency 1?

### ISSUE THREAD

**Issue by JanVeb** [liangqi/chinese-frequency-word-list#4]
的	de	1
frequency for 的	must be wrong, that's one of most frequent words in Chinese language
there are many words like this

是 | 2
-- | --
在 | 3
一 | 4
不 | 5
有 | 6
这 | 7
个 | 8
上 | 9
也 | 10
他 | 11
人 | 12
就 | 13
对 | 14
说 | 15
我 | 16
要 | 17
到 | 18
大 | 19

Do I have this wrong?
The lover the number the higher the frequency?

**Comment by liangqi** [comment]
@JanVeb Hi, I think you are talking about characters instead of words. I would like to consider 的 as the 's in someone's, then it isn't a word.

**Comment by JanVeb** [comment]
hm, okay, so why is it then in a word list?

**Comment by liangqi** [comment]
I was wrong. Lower value means more frequently.
